### PR TITLE
Possible enhancement

### PR DESCRIPTION
**Pull request by teknowledgist**
I **think** this will give a more detailed error text.  I don't know C#, so I'm not sure.  Comments are welcome.

Also, made a personal preference change to compare `variable` to `null` rather than comparing `null` to `variable`.

### CODE REVIEW

**Comment by teknowledgist** [comment]
@zunderscore Do you know C# (and PoSh) well enough to say whether the `throw` I added will enhance the error message output to the user?

**Comment by zunderscore** [comment]
It may. At the very least, I don't think it would hurt. But I would defer to someone who knows Win32 exception handling better than me.

**Comment by teknowledgist** [comment]
@AlanMcBee Would you be willing to share how you got [the additional information when attempting the Cascadia font install](https://github.com/zunderscore/chocolatey-packages/issues/3#issuecomment-687314431).  Specifically, the `WARNING: Exception: The requested operation cannot be performed on a file with a user-mapped section open.`  

I would like to be able to fold that level of error message into this enhancement of the Chocolatey-font-helpers.extension package, but in my fumbling around with understanding C# code, it appears to me that [for the AddFontResource() function of gdi32.dll](https://docs.microsoft.com/en-us/windows/win32/api/wingdi/nf-wingdi-addfontresourcea) that "No extended error information is available."  How did you get that error message when there isn't error information available?

Thanks!

**Comment by AlanMcBee** [comment]
All I did was write out the actual exception in the catch{} block. Something like this:

Uninstall-ChocolateyFont.ps1:
``` powershell 
...
      catch
      {
         Write-Warning "An error occured removing '$Item'."
         Write-Warning "Exception: $($_.Exception.Message)"  # This is the only thing I added
         Write-Warning "$($error[0].ToString())"
         $error.clear()
      }
...
```

Apparently (and I did not know this before), the `$Error` variable is not always populated with details from the underlying problem.

In general, nearly every error that is thrown by something in Windows will originate with an exception, so the `$_` variable in the catch block should always have something in it. The `$_` (or `$PSItem`) is an `ErrorRecord` object, but I would expect it to always have something in its `Exception` property.

Some info I found useful:

- https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_try_catch_finally?view=powershell-7#accessing-exception-information

- https://docs.microsoft.com/en-us/powershell/scripting/learn/deep-dives/everything-about-exceptions?view=powershell-7

**Pull request merged**
