### PR TITLE
Adjust case for remote-package-registry

### PR DESCRIPTION
**Pull request by jmarrec**
The casing is wrong, the R shouldn't be in caps, should be `--remote-package-repository`

"miktexsetup.exe: --Remote-package-repository=https://ctan.math.illinois.... unknown option"

### CODE REVIEW

**Comment by teknowledgist** [comment]
@jmarrec I am working on another update too (for when building a local repository and the default download mirror is broken), but I will push an updated package as soon as I have that working.  Sorry for the delay.  

Thanks for the PR, BTW!  I didn't realize the switch was case-sensitive (most Windows apps are not).

**Comment by jmarrec** [comment]
Do you have a rough idea of when you think your feature will be complete?

For context, I'm using choco to install miktex on a github actions runner that will build my C++ program and its latex documentation, and I _very_ regularly get into troubles with a specific mirror (`mirror.koddos.net`) that makes my workflow fail, which is annoying.

Depending on when you think you'll have this PR content up in the recipe, I will either wait (if it's a few days) or do a workaround without choco.

thanks!

**Comment by teknowledgist** [comment]
@jmarrec I just pushed an updated package with your PR and a new `/Mirror` switch for downloading from a remote repository.  (`/RepoPath` also works, but `/Mirror` allows for simultaneously creating a local repo using `/RepoPath`.)

It might take a few days for the moderators to approve the package (assuming it passes automatic validation).  You can always use the `--version 20.10.0.20201030` switch to use it once validated.

**Comment by jmarrec** [comment]
Awesome, thanks a lot!

**Comment by jmarrec** [comment]
@teknowledgist I am having a couple of problems with the new version:

* Passing RepoPath:<url> fails because it is *not* defaulting --local-repository. Same goes if passing only `Miror:<url>`
* When I use this `choco install --verbose -y --no-progress miktex --version 20.10.0.20201030 --params '"/RepoPath:""C:\Users\julien\AppData\Local\Temp\chocolatey\MiKTeX-repository"" /Mirror:https://ctan.math.illinois.edu"'`, I get a weird null-value error:

```
VERBOSE: Importing alias 'Remove-BinFile'.
VERBOSE: Importing alias 'Start-ChocolateyProcess'.
Environment Vars (like PATH) have changed. Close/reopen your shell to
 see the changes (or in powershell/cmd.exe just type `refreshenv`).
 The install of miktex was successful.
  Software install location not explicitly set, could be in package or
  default install location if installer.

Chocolatey installed 1/2 packages. 1 packages failed.
 See the log for details (C:\ProgramData\chocolatey\logs\chocolatey.log).

Failures
 - miktex.install (exited -1) - Error while running 'C:\ProgramData\chocolatey\lib\miktex.install\tools\chocolateyinstall.ps1'.
 See log for details.
```

Am I mis-using the recipe?

**Comment by teknowledgist** [comment]
@jmarrec A few comments:

* The v20.10.0.20201030 has been approved, so you don't need the `--version` switch.
* If you want to use a specific remote repository (i.e. ctan.math.illinois.edu), you have to provide the full URL, not just the server.  I did write the chocolateyinstall.ps1 script (i.e. recipe -- your a munki user aren't you? 😄 ) so any time the `/mirror` parameter is called (valid or not), the Chocolatey log will get a list of all the "official" ctan repositories for MiKTeX.  For example, I think what you want to be using is `https://ctan.math.illinois.edu/systems/win32/miktex/tm/packages/`.
* It doesn't make any sense to set the `/RepoPath` value to a temp location.  The intent of that parameter is if you want to have a "permanent" repository to be shared with other users.  For example, you could establish a local repository on a file or web server using that parameter and then all the other computers on your network could use `/RepoPath` to point to that remote, shared location as their repository.  Thus, only one computer needs to download the massive MiKTeX set from the internet, and the rest of the file transfers (to potentially hundreds of machines) would be internal.  
* I have discovered a limitation of the MiKTeX setup utility that means (despite my claims in the description of the package) the `/Mirror` parameter cannot be used alone.  It will only work if `/RepoPath` is also defined.  

Finally, just to point it out, the `miktex` package is a "meta-package".  It is an empty package with a dependency on the "real" package, `miktex.install`.  You don't really need to install the 'miktex' package.  IMHO, it just confuses the issue, but I kinda have to keep the meta-package for historical reasons.

Let me know if you still have questions.

**Comment by jmarrec** [comment]
Thanks for your comments @teknowledgist.

I use the term recipe because I'm more familiar with homebrew (package manager for macOS) and even more lately with conan (a C++ package manager).

I realized the miktex is a virtual package for miktex.install yeah.

I have tried like 10 different combinations of (URL full or shortened to domain) and whether I'm passing RepoPath and/or Mirror. I never managed to run single command that succesfully set the Mirror and installs miktex, do you have one please?

Pointing RepoPath and Mirror to the same full URL doesn't work, since it's complaining about missing local package directory.

```
choco install -y --no-progress miktex --params '"/RepoPath:https://ctan.math.illinois.edu/systems/win32/miktex/tm/packages/ /Mirror:https://ctan.math.illinois.edu/systems/win32/miktex/tm/packages/"' 
````

what I get in the chocolatey.log:

```
2020-11-01T09:22:36.9281114Z 2020-11-01 09:22:22,621 3088 [DEBUG] - Running 'Get-UninstallRegistryKey' for 'miktex.install' with SoftwareName:'miktex*'
2020-11-01T09:22:36.9281929Z 2020-11-01 09:22:22,622 3088 [INFO ] - VERBOSE: Retrieving all uninstall registry keys
2020-11-01T09:22:36.9282459Z 2020-11-01 09:22:23,221 3088 [DEBUG] - Registry uninstall keys on system: 765
2020-11-01T09:22:36.9283138Z 2020-11-01 09:22:23,222 3088 [DEBUG] - Error handling check: 'Get-ItemProperty' fails if a registry key is encoded incorrectly.
2020-11-01T09:22:36.9283971Z 2020-11-01 09:22:23,806 3088 [DEBUG] - Found 0 uninstall registry key(s) with SoftwareName:'miktex*'
2020-11-01T09:22:36.9284565Z 2020-11-01 09:22:23,814 3088 [INFO ] - Installing from MiKTeX repository.
2020-11-01T09:22:36.9286711Z 2020-11-01 09:22:23,846 3088 [DEBUG] - Running Start-ChocolateyProcessAsAdmin -validExitCodes '0' -statements '--verbose --remote-package-repository="https://ctan.math.illinois.edu/systems/win32/miktex/tm/packages/" --package-set=basic --shared install ' -workingDirectory 'C:\ProgramData\chocolatey\lib\miktex.install\tools' -exeToRun 'C:\ProgramData\chocolatey\lib\miktex.install\tools\miktexsetup.exe' 
2020-11-01T09:22:36.9288971Z 2020-11-01 09:22:23,850 3088 [DEBUG] - Unable to use current location for Working Directory. Using Cache Location instead.
2020-11-01T09:22:36.9289718Z 2020-11-01 09:22:23,882 3088 [DEBUG] - Test-ProcessAdminRights: returning True
2020-11-01T09:22:36.9291482Z 2020-11-01 09:22:23,895 3088 [DEBUG] - Elevating permissions and running ["C:\ProgramData\chocolatey\lib\miktex.install\tools\miktexsetup.exe" --verbose --remote-package-repository="https://ctan.math.illinois.edu/systems/win32/miktex/tm/packages/" --package-set=basic --shared install ]. This may take a while, depending on the statements.
2020-11-01T09:22:36.9293246Z 2020-11-01 09:22:23,960 3088 [ERROR] - miktexsetup.exe: no local package directory found
2020-11-01T09:22:36.9294809Z 2020-11-01 09:22:23,962 3088 [DEBUG] - Command ["C:\ProgramData\chocolatey\lib\miktex.install\tools\miktexsetup.exe" --verbose --remote-package-repository="https://ctan.math.illinois.edu/systems/win32/miktex/tm/packages/" --package-set=basic --shared install ] exited with '1'.
2020-11-01T09:22:36.9297360Z 2020-11-01 09:22:24,005 3088 [ERROR] - ERROR: Running ["C:\ProgramData\chocolatey\lib\miktex.install\tools\miktexsetup.exe" --verbose --remote-package-repository="https://ctan.math.illinois.edu/systems/win32/miktex/tm/packages/" --package-set=basic --shared install ] was not successful. Exit code was '1'. See log for possible error messages.
2020-11-01T09:22:36.9302114Z 2020-11-01 09:22:24,007 3088 [DEBUG] - Built-in PowerShell host called with ['[System.Threading.Thread]::CurrentThread.CurrentCulture = '';[System.Threading.Thread]::CurrentThread.CurrentUICulture = ''; & import-module -name 'C:\ProgramData\chocolatey\helpers\chocolateyInstaller.psm1'; & 'C:\ProgramData\chocolatey\helpers\chocolateyScriptRunner.ps1' -packageScript 'C:\ProgramData\chocolatey\lib\miktex.install\tools\chocolateyinstall.ps1' -installArguments '' -packageParameters '/RepoPath:https://ctan.math.illinois.edu/systems/win32/miktex/tm/packages/ /Mirror:https://ctan.math.illinois.edu/systems/win32/miktex/tm/packages/''] exited with '1'.
2020-11-01T09:22:36.9305759Z 2020-11-01 09:22:24,012 3088 [DEBUG] - Calling command ['"C:\windows\System32\shutdown.exe" /a']
2020-11-01T09:22:36.9306401Z 2020-11-01 09:22:24,082 3088 [DEBUG] - Command ['"C:\windows\System32\shutdown.exe" /a'] exited with '1116'
2020-11-01T09:22:36.9307127Z 2020-11-01 09:22:24,381 3088 [DEBUG] - Capturing package files in 'C:\ProgramData\chocolatey\lib\miktex.install'
2020-11-01T09:22:36.9307993Z 2020-11-01 09:22:24,400 3088 [DEBUG] -  Found 'C:\ProgramData\chocolatey\lib\miktex.install\miktex.install.nupkg'
2020-11-01T09:22:36.9308796Z   with checksum 'D1B467BDCABD144662BAD5E1025A2837'
2020-11-01T09:22:36.9309612Z 2020-11-01 09:22:24,400 3088 [DEBUG] -  Found 'C:\ProgramData\chocolatey\lib\miktex.install\miktex.install.nuspec'
2020-11-01T09:22:36.9310442Z   with checksum '818C7AA531E637076993CEEB64D3AC15'
[...]
```

**Comment by teknowledgist** [comment]
@jmarrec Sorry for the delay and the problem(s) you are encountering.  I re-read the documentation on the setup utility, and realized I misinterpreted something.  I've adjusted the `ChocolateyInstall.ps1` script (i.e. the "recipe" 😉 ), and I think/hope it will resolve the issue.  

There was also an new milestone released over the weekend (v20.11), so I pushed that new Chocolatey package.

**Comment by teknowledgist** [comment]
Based on what you were using before, I was able to do:

    choco install miktex.install -y --no-progress --params '"/Mirror:https://ctan.math.illinois.edu/systems/win32/miktex/tm/packages/"'

**Pull request merged**
