### PR TITLE
- address checksum failure after source url pkg download verification

### PR DESCRIPTION
**Pull request by jhelfman**
address build failure after post-build fail verification

### CODE REVIEW

**Comment by teknowledgist** [comment]
Thank you for pointing out the checksum changed, but it was because the version changed.  The new version has been pushed.

**Comment by jhelfman** [comment]
> Thank you for pointing out the checksum changed, but it was because the version changed. The new version has been pushed.

Ok thanks. I will try tomorrow, however the errors I received were after new version was pushed.

**Comment by teknowledgist** [comment]
Right, that is because the new version hasn't been approved by the moderators.  You were actually downloading the previous package (in which the checksums don't match the current download).  Check out [the version history of the package](https://chocolatey.org/packages/onedrive#versionhistory).

Eventually, after enough releases without incident, the package will be "trusted" by the public repository/moderators, and approval of the package will happen within a couple hours of submitting it.  Until then, there is a manual review, and if you want to install an unapproved package you will have to specify the version like this:

    choco install onedrive --version <full version number>

**Comment by jhelfman** [comment]
> Right, that is because the new version hasn't been approved by the moderators. You were actually downloading the previous package (in which the checksums don't match the current download). Check out [the version history of the package](https://chocolatey.org/packages/onedrive#versionhistory).
> 
> Eventually, after enough releases without incident, the package will be "trusted" by the public repository/moderators, and approval of the package will happen within a couple hours of submitting it. Until then, there is a manual review, and if you want to install an unapproved package you will have to specify the version like this:
> 
> ```
> choco install onedrive --version <full version number>
> ```

Ok thanks for the update and notes on the installation. Being a packager for another operating system, I find this process a little strange in that it seems to break standard installation process while new package is awaiting approval.

**Comment by teknowledgist** [comment]
Yeah, Chocolatey and the public repository is not without flaws.  It is a project to build a package management system on an OS that didn't have one.  It's **way** better than nothing, and many of the annoyances are due to trying to keep security and integrity relatively high on a free, public repository with limited resources.

I guess Microsoft is (finally) trying to build a package management system with [WinGet](https://github.com/microsoft/winget-cli), but I haven't delved too deeply into it.  We'll see if they can get enough lift with it.

**Pull request closed without merging**
