### PR TITLE
PDF24 Creator - use download.pdf24.org

### PR DESCRIPTION
**Pull request by sz5000**
Please always use download.pdf24.org because download.pdf24.org distributes the load to different servers. Currently there are 5 servers (downloadX.pdf24.org) which run in parallel and each of them is limited in bandwidth. Currently we see too much traffic on download2.pdf24.org. So, please use download.pdf24.org, if this is possible and follow the redirect.

### CODE REVIEW

**Comment by teknowledgist** [comment]
@sz5000 Good to know.  Sorry to have caused a problem.  I'm pushing an intermediate package version to correct this.

**Comment by sz5000** [comment]
Thank you.

**Comment by sz5000** [comment]
There are now also x86 builds of the current version.

Download URLs of x86 builds:
https://download.pdf24.org/pdf24-creator-11.11.1-x86.exe
https://download.pdf24.org/pdf24-creator-11.11.1-x86.msi

Download URLs of x64 builds:
https://download.pdf24.org/pdf24-creator-11.11.1-x64.exe
https://download.pdf24.org/pdf24-creator-11.11.1-x64.msi

Just as information, because I do not know if it makes sense to add these x86 builds.

**Comment by teknowledgist** [comment]
Good to know!  I'll definitely fold those in soon.  Thanks!

**Pull request merged**
